defaults:
  - scope:
      path: ""
      type: "posts"
    values:
      layout: "post"
  - scope:
      path: ""
    values:
      layout: "default"

collections:
  tags:
    output: true

markdown: kramdown
highlighter: rouge

kramdown:
  syntax_highlighter: rouge
